server: 
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    eureka-service-url-poll-interval-seconds: 1
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  output:
    ansi:
      enabled: always
