eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

server:
  port: 8085
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${SERVER:localhost}:${PORT:5432}/${DB_NAME:cinema_collection_service_db}
    url: jdbc:postgresql://localhost:5444/cinema_collection_service_db
    username: postgres
    password: root
  sql:
    init:
      platform: postgres
  main:
    banner-mode: off
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
  tomcat:
    uri-encoding: UTF-8
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: false
